#!/bin/sh
c0="${reset}${blue}"                # first color

## OUTPUT

cat <<EOF

${c0}        /\\        
${c0}       /  \\      
${c0}      /\`'.,\\   
${c0}     /     ',     
${c0}    /      ,\`\\    
${c0}   /   ,.'\`.  \\   
${c0}  /.,'\`     \`'.\\ 

EOF
